# Generated by Django 5.0.1 on 2024-02-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_producto_sucursal_usuario_delete_crear_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='producto',
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
