# Generated by Django 5.0.1 on 2024-02-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_alter_sucursal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjetaCredito', models.BooleanField()),
                ('tarjetaDebito', models.BooleanField()),
                ('transferencia', models.BooleanField()),
                ('efectivo', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
